### ISSUE TITLE
yo i am getting this issue can you help

### ISSUE THREAD

**Issue by ghost** [meet447/Chipling-AI#1]
C:\Users\HP\Desktop\Chipling-AI-main>python app.py
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Chipling-AI-main\app.py", line 21, in <module>
    db = firebase.database()
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pyrebase\pyrebase.py", line 67, in database
    return Database(self.credentials, self.api_key, self.database_url, self.requests)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pyrebase\pyrebase.py", line 200, in __init__
    if not database_url.endswith('/'):
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by meet447** [comment]
### Step 1: Create a Firebase Project

1. Go to the [Firebase Console](https://console.firebase.google.com/).
2. Click on "Add Project."
3. Enter a name for your project and choose your preferred country/region.
4. Click "Create Project."

### Step 2: Set up Firebase Authentication

1. In the Firebase Console, go to the "Authentication" section.
2. Enable the "Sign-in method" that you prefer (Email/Password)
3. Follow the instructions to set up authentication methods.

### Step 3: Get Firebase Configuration

1. In the Firebase Console, click on the gear icon in the left panel to go to "Project Settings."
2. In the "General" tab, scroll down to the "Your apps" section.
3. Click on the "</>" icon to add a web app to your project.
4. Register your app by providing a nickname (e.g., "MyApp").
5. Click "Register App."
6. Copy the generated configuration.

### Step 4: Create a .env file

1. Create a new file in your project root directory and name it `.env`.
2. Open the `.env` file with a text editor.

### Step 5: Add Firebase Configurations to .env

Paste the following lines into your `.env` file and replace the placeholders with the actual values from your Firebase project.

```env
FIREBASE_API_KEY=your_api_key
FIREBASE_AUTH_DOMAIN=your_auth_domain
FIREBASE_PROJECT_ID=your_project_id
FIREBASE_STORAGE_BUCKET=your_storage_bucket
FIREBASE_MESSAGING_SENDER_ID=your_messaging_sender_id
FIREBASE_APP_ID=your_app_id
FIREBASE_MEASUREMENT_ID=your_measurement_id
FIREBASE_DATABASE_URL=your_database_url
```

**Comment by ghost** [comment]
btw can we talk on discord im kinda new to github idk how to use it

**Comment by ghost** [comment]
and yes i did configure a project but i didnt get a database url
